name: Process Metadata Submission

on:
    workflow_dispatch:
    issues:
        types:
            - opened
            - edited
            - labeled

jobs:
  process_metadata_submission:
    if: |
      contains(github.event.issue.labels.*.name, 'metadata submission') &&
      !contains(github.event.issue.labels.*.name, 'draft submission')
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v7

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'
  
        - name: Install dependencies
          run: pip install --upgrade pip
  
        - name: Debug Issue Details
          env:
            env_issue_body: ${{ github.event.issue.body }}
          run: |
            echo "Env issue body: $env_issue_body"
            echo "Issue title: ${{ github.event.issue.title }}"
            echo "Issue labels: ${{ toJson(github.event.issue.labels) }}"
  
        - name: Process Metadata Submission
          env:
            env_issue_body: ${{ github.event.issue.body }}
          run: |
            python process_appsubmission.py "${{ github.event.issue.title }}" "$env_issue_body"
  
        - name: Commit and Push Changes
          run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "github-actions@github.com"
            git add .
            git commit -m "Add metadata for ${{ github.event.issue.title }}"
            git push
